---
schemaVersion: resourceModel/1.0
application:
  name: MortgageApplication
  description: MortgageApplication constraints
  constraints:
  - id: program-name-prefix
    prefix: EPS
  - id: mapset-name-prefix
    prefix: EPSM
  - id: transaction-name-prefix
    prefix: EPS 
  - id: resource-name-prefix
    prefix: EPS 
