# Application properties used by zAppBuild/languages/Transfer_USS.groovy

#
# Default deployType when not overridden in file.properties
transfer_uss_deployType=USS

#
# Default target USS staging directory under workspace
# transfer_uss_targetDir=${props.workspace}/ussfiles
